#!/bin/bash

readonly BACKUP_COMPRESSOR="lbzip2"
readonly BACKUP_ENCRYPTOR="java -jar cryptout.jar --encrypt --aes256"


dir="${*: -2:1}"
backup_dir="${*: -1:1}"


full_backup=false
compress_backup=false
encrypt_backup=false
backup_public_key=""

while [ $# -gt 2 ]
do
	case "$1" in
	--full) full_backup=true
		;;
		--compress) compress_backup=true
				;;
		--encrypt) encrypt_backup=true
				case "$2" in
				--*) echo "Missing argument for option: $1"
						exit 1 # replace with proper exit code
						;;
				*) backup_public_key="$2"
						shift
						;;
				esac
				;;
		--*) echo "Unknown option: $1"
				;;
#	*) echo "Argument: $1"
#		;;
	esac
	shift
done


backup_name="$(date +'%Y-%m-%d-%H-%M')"
backup_extension=$([ "$full_backup" = true ] && echo ".full.backup" || echo ".backup")

if [[ "$backup_dir" != *"/" ]]
then
	backup_dir="$backup_dir/"
fi

backup_path="$backup_dir$backup_name"

if [[ -f "$backup_path$backup_extension" ]] || [[ -f "$backup_path-0$backup_extension" ]]
then
	index="1"
	backup_new_path="$backup_path-$index"
	while [[ -f "$backup_new_path$backup_extension" ]]
	do
		index=$[$index+1]
		backup_new_path="$backup_path-$index"
	done
#	if [[ -f "$backup_path$backup_extension" ]]
#	then
#		mv "$backup_path$backup_extension" "$backup_path-0$backup_extension"
#	fi
	backup_path="$backup_new_path"
fi

backup_path="$backup_path$backup_extension"


mkdir -p "$backup_dir"
touch "$backup_path"


backup_log="${backup_dir}backup.log"
if [ "$full_backup" = true ]
then
	if [[ -f "$backup_log" ]]
	then
		rm "$backup_log"
	fi
else
	if [[ -f "$backup_log" ]]
	then
		cp "$backup_log" "$backup_log.tmp"
	fi
	backup_log="$backup_log.tmp"
fi


echo Starting backup of "$dir" to "$backup_path" ...

# test if this works
tar -c -g "$backup_log" -f - "$dir" \
$([ "$compress_backup" = true ] && echo "| $BACKUP_COMPRESSOR" || echo "") \
$([ "$encrypt_backup" = true ] && echo "| $BACKUP_ENCRYPTOR $backup_public_key" || echo "") \
> "$backup_path"

echo Finished backup of "$dir"

if [ "$full_backup" = false ]
then
	rm "$backup_log"
fi
